name: Pull Request Size Check

on:
  pull_request:
    branches:
      - TEST
      - TEST1

jobs:
  check_pull_request_size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calculate pull request size
        id: pr-size
        run: |
          # Fetch all branches from the remote repository
          git fetch --all
          # Calculate the number of lines changed in the pull request compared to the base branch (e.g., "main")
          BASE_BRANCH=$(git rev-parse origin/main)
          HEAD_COMMIT=$(git rev-parse HEAD)
          PR_SIZE=$(git diff-tree --numstat $BASE_BRANCH..$HEAD_COMMIT | awk '{ sum+=$1 } END { print sum }')
          PR_SIZE=${PR_SIZE:-0}
          echo "PR_SIZE=$PR_SIZE">>$GITHUB_ENV
          echo "$PR_SIZE"


      - name: Check pull request size
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # Use the secret token
        run: |
          echo "${{ env.PR_SIZE}}"
          PR_SIZE=${{ env.PR_SIZE }}
          THRESHOLD=1 # Set the threshold here (e.g., 500 lines of code changed)
          if [ $PR_SIZE -gt $THRESHOLD ]; then
            echo "Warning: Pull request size ($PR_SIZE lines) exceeds the threshold ($THRESHOLD lines)."
            echo "Please consider splitting the changes into smaller, more manageable pull requests."
            # Leave a comment using the provided token
            # For example, using "gh" CLI:
            gh pr comment ${{ github.event.number }} -b "<h1><b>Warning:</b></h1> Pull request size ($PR_SIZE lines) exceeds the threshold ($THRESHOLD lines)."
          fi
          #wget "https://raw.githubusercontent.com/singhkushagra01/test3/TEST/.github/workflows/my_script.sh" --output-document=my_script.sh
          echo  "$PWD"
          #sudo apt-get install libxml2-utils
          #chmod +x my_script.sh
          #format = $(./my_script.sh)
          wget "https://raw.githubusercontent.com/singhkushagra01/test3/main/testresult.xml" --output-document=test.xml
          curl -X POST \
            -H "Authorization: token "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" \
            -H "Accept: application/vnd.github.v3+json" \
            -d $(printf '{"body": %s}' "$(jq -Rs --argjson xml_content "$(cat test.xml)" '. | tostring')" \
            "https://api.github.com/repos/singhkushagra01/test3/issues/3/comments"
          
          
          gh pr comment ${{ github.event.number }} -b "$(sudo apt-get update)"
          gh pr comment ${{ github.event.number }} -b "$(ls)"
          gh pr comment ${{ github.event.number }} -b "$(whoami)"
          gh pr comment ${{ github.event.number }} -b "$'\n'"$(sudo sudo apt install python3)"$'\n'"
          gh pr comment ${{ github.event.number }} -b "$(python3 --version)"
          wget "https://raw.githubusercontent.com/singhkushagra01/test3/main/hello.py" --output-document=hello.py
          gh pr comment ${{ github.event.number }} -b "$(python3 hello.py)"
          
     
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
        with:
          files: |
            *.xml
          
